# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache2-ClickPath
version:      1.4
version_from: lib/Apache2/ClickPath.pm
installdirs:  site
requires:
    Apache::Test:                  
    mod_perl:                      1.999022

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
